// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MH_GameplayTags
{
	//InputTags
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipWeapon);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipWeapon);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_GapllingHook);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Run);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combo_Y);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combo_B);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combo_YB);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combo_LT);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combo_RT);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combo_LTY);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Combo_LTB);
	
	//AbilityTag
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_LongSword);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UnEquip_LongSword);
	
	
	
	
	//WeaponTag
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_LongSword);
	//EventTags
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Eevent_Equip_LongSword);
	MH_RECREATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Eevent_UnEquip_LongSword);
	
}
